# Configuration file for arXiv Paper Monitor

# Maximum total number of papers to fetch across all categories in a single run.
# This acts as a safeguard if the number of papers published today is very large.
max_total_results: 1000

# --- Relevance Checking Method ---
# Determines the overall method used for checking paper relevance.
# Options: "keyword" or "llm"
relevance_checking_method: "keyword"

# Paper source configuration
paper_source:
  type: "arxiv"  # Options: arxiv
  arxiv:
    categories: [  # ArXiv categories to search - find categories here: https://arxiv.org/category_taxonomy
                  "math-ph",          # Mathematical Physics
                  "physics.atm-clus", # Atomic and Molecular Clusters
                  "physics.comp-ph",  # Computational Physics
                  "quant-ph",         # Quantum Physics
                  "physics.data-an",  # Data Analysis, Statistics and Probability
                  "math.IT",          # Information Theory
                  "math.NA",          # Numerical Analysis
                  "math.OC",          # Optimization and Control
                  "cs.AI",            # Artificial Intelligence
                  "cs.CE",            # Computational Engineering, Finance, and Science
                  "cs.IT",            # Information Theory
                  "cs.LG"             # Machine Learning
                ]
    # arXiv categories to monitor
    keywords: [ # Keywords to filter papers (case insensitive)
               "tensor network",
               "quantum circuit simulation",
               "expectation value estimation",
               "contraction path",
               "Quantum Approximate Optimization Algorithm",
               "QAOA",
               "variational quantum eigensolver",
               "VQE",
               ]
    fetch_window: 24  # Hours to look back for papers

# Relevance checker specific settings (used depending on relevance_checking_method)
relevance_checker:
  llm:
    provider: "groq"  # Options: groq, custom
    api_key: ""  # Your Groq API key (optional if using custom provider)
    model: "llama-3.1-8b-instant"  # Groq model to use
    prompt: "Is this paper relevant to my research on large language models and their applications in natural language processing? Consider both technical depth and practical implications."
    batch_size: 10  # Number of papers to process in each batch (0 for no batching)
    confidence_threshold: 0.7  # Minimum confidence score to consider a paper relevant

# Output configuration
output:
  file: "relevant_papers.txt"  # File to save relevant papers
  format: "markdown"  # Output format (markdown, plain)
  include_confidence: true  # Whether to include confidence scores in output
  include_explanation: true  # Whether to include LLM explanations in output

# Schedule configuration
schedule:
  run_time: "09:00"  # Daily run time (24-hour format)
  timezone: "UTC"  # Timezone for run time
