# Configuration file for arXiv Paper Monitor

# --- Active Sources ---
# List of paper sources to fetch from. Corresponds to keys under 'paper_source'.
active_sources:
  - "arxiv"
  - "biorxiv"

# Maximum total number of papers to fetch across all categories in a single run.
# This acts as a safeguard if the number of papers published today is very large.
max_total_results: 100 # Note: This might need adjustment depending on how sources handle limits.

# --- Relevance Checking Method ---
# Determines the overall method used for checking paper relevance.
# Options: "keyword" or "llm"
relevance_checking_method: "keyword"

# --- Paper Source Configuration ---
# Contains settings for each individual paper source.
paper_source:
  # Settings for arXiv
  arxiv:
    categories: [  # ArXiv categories to search - find categories here: https://arxiv.org/category_taxonomy
                  "math-ph",          # Mathematical Physics
                  "physics.atm-clus", # Atomic and Molecular Clusters
                  "physics.comp-ph",  # Computational Physics
                  "quant-ph",         # Quantum Physics
                  "physics.data-an",  # Data Analysis, Statistics and Probability
                  "math.IT",          # Information Theory
                  "math.NA",          # Numerical Analysis
                  "math.OC",          # Optimization and Control
                  "cs.AI",            # Artificial Intelligence
                  "cs.CE",            # Computational Engineering, Finance, and Science
                  "cs.IT",            # Information Theory
                  "cs.LG"             # Machine Learning
                ]
    # Keywords specific to filtering papers fetched ONLY from arXiv
    # Used only when relevance_checking_method is "keyword".
    keywords: [
               "tensor network",
               "quantum circuit simulation",
               "expectation value estimation",
               "contraction path",
               "Quantum Approximate Optimization Algorithm",
               "QAOA",
               "variational quantum eigensolver",
               "VQE",
               ]
    fetch_window: 4 # Days to look back for papers (Uses global if not set here)

  # Settings for bioRxiv/medRxiv
  biorxiv:
    # Which server to query: "biorxiv" or "medrxiv"
    server: "biorxiv"
    # bioRxiv/medRxiv subject categories (case-sensitive, use underscores for spaces)
    # Examples: "cell_biology", "genomics", "neuroscience"
    # Find categories on the bioRxiv/medRxiv websites. Leave empty [] to search all.
    categories: [
                  "Biochemistry",
                  "Bioinformatics",
                  "Neuroscience",
                  "Plant Biology"
                ]
    # Keywords specific to filtering papers fetched ONLY from bioRxiv/medRxiv
    # Used only when relevance_checking_method is "keyword".
    keywords: [
               "systems biology",
               "computational biology",
               "protein",
               "sequencing",
               "brain"
              ]
    fetch_window: 4 # Days to look back for papers (Uses global if not set here)



# Relevance checker specific settings (used depending on relevance_checking_method)
relevance_checker:
  llm:
    provider: "groq"  # Options: groq, custom
    groq: # Settings specific to the "groq" provider
      # SECURITY: Consider using environment variable (GROQ_API_KEY) instead!
      api_key: "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"  # Your Groq API key
      model: "llama-3.1-8b-instant"  # Groq model to use
      prompt: "Is this paper relevant to my research on tensor networks for quantum circuit simulations, or quantum circuit simulation in general?"
      batch_size: 5  # Number of papers to process in each batch (0 for no batching)
      confidence_threshold: 0.7  # Minimum confidence score to consider a paper relevant
      batch_delay_seconds: 15 # Seconds to wait between consecutive batch API calls (adjust based on rate limits)

# Output configuration
output:
  file: "relevant_papers.txt"  # File to save relevant papers
  format: "markdown"  # Output format (markdown, plain)
  include_confidence: true  # Whether to include confidence scores in output
  include_explanation: true  # Whether to include LLM explanations in output

# Schedule configuration
schedule:
  run_time: "09:00"  # Daily run time (24-hour format)
  timezone: "UTC"  # Timezone for run time

# --- Notifications Configuration ---
notifications:
  # --- Enable/Disable Email ---
  # Set this to 'true' to enable sending summary emails, 'false' to disable.
  # If false, the settings below are ignored.
  send_email_summary: true

  # --- Recipient Emails ---
  # A list of email addresses that will receive the summary email.
  # Add each recipient on a new line starting with '- '.
  email_recipients:
    - "madsen3008@gmail.com"
    # - "another_email@example.org"

  # --- Sender Email Credentials ---
  # IMPORTANT: Storing credentials directly in this file is INSECURE,
  # especially if you commit it to version control (like Git).
  # It's strongly recommended to use one of these alternatives:
  #   1. Environment Variables: Load the address/password from the system environment.
  #   2. Secrets Manager: Use a dedicated service (AWS Secrets Manager, HashiCorp Vault, etc.).
  #   3. App Passwords (Gmail/Google Workspace): If using Gmail with 2-Factor Authentication (2FA) enabled,
  #      you MUST generate an "App Password" specifically for this application.
  #      See: https://myaccount.google.com/apppasswords
  email_sender:
    # The email address the summary email will be sent FROM.
    address: "madsen3008@gmail.com"

    # The email password for the sender address OR the generated App Password (e.g. if using Gmail with 2FA enabled).
    password: "nlsj yket flvw hfyo"

  # --- SMTP Server Details ---
  # These settings tell the script how to connect to your email provider's sending server.
  # You often need to look these up for your specific email provider (e.g., search "Gmail SMTP settings").
  smtp:
    # The hostname of the SMTP server.
    # Common examples:
    #   - Gmail: "smtp.gmail.com"
    #   - Outlook/Office365: "smtp.office365.com"
    #   - Yahoo: "smtp.mail.yahoo.com"
    server: "smtp.gmail.com"

    # The port number for the SMTP server connection.
    # Common examples:
    #   - 587 (Recommended for TLS/STARTTLS encryption)
    #   - 465 (Used for older SSL encryption)
    #   - 25 (Standard SMTP, often blocked, usually unencrypted - avoid if possible)
    # Port 587 is the most common for modern secure connections.
    port: 587
