# ArXiv categories to search (e.g., cs.AI, cs.LG, math.AP)
# Find categories here: https://arxiv.org/category_taxonomy
categories:
  - "cs.AI"
  - "cs.LG"
  - "stat.ML"

# Filtering criteria
# Option 1: List of keywords (case-insensitive)
# If any keyword is found in the title or abstract, the paper is considered relevant.
keywords:
  - "transformer"
  - "diffusion model"
  - "reinforcement learning"

# Option 2: A subject prompt (more advanced, requires NLP approach - not implemented by default)
# subject_prompt: "Papers discussing novel methods for large language model alignment."

# Maximum total number of papers to fetch across all categories in a single run.
# This acts as a safeguard if the number of papers published today is very large.
max_total_results: 500

# Time of day to run the check (HH:MM format, 24-hour clock)
run_time_daily: "08:00"

# File to store relevant papers (optional, creates if it doesn't exist)
output_file: "relevant_papers.txt"

# Paper source configuration
paper_source:
  type: "arxiv"  # Options: arxiv
  arxiv:
    categories: ["cs.AI", "cs.LG", "cs.CL"]  # arXiv categories to monitor
    keywords: ["large language model", "transformer", "attention"]  # Keywords to filter papers
    fetch_window: 24  # Hours to look back for papers

# Relevance checking configuration
relevance_checker:
  type: "keyword"  # Options: keyword, llm
  llm:
    provider: "groq"  # Options: groq, custom
    api_key: ""  # Your Groq API key (optional if using custom provider)
    model: "llama-3.1-8b-instant"  # Groq model to use
    prompt: "Is this paper relevant to my research on large language models and their applications in natural language processing? Consider both technical depth and practical implications."
    batch_size: 10  # Number of papers to process in each batch (0 for no batching)
    confidence_threshold: 0.7  # Minimum confidence score to consider a paper relevant

# Output configuration
output:
  file: "relevant_papers.txt"  # File to save relevant papers
  format: "markdown"  # Output format (markdown, plain)
  include_confidence: true  # Whether to include confidence scores in output
  include_explanation: true  # Whether to include LLM explanations in output

# Schedule configuration
schedule:
  run_time: "09:00"  # Daily run time (24-hour format)
  timezone: "UTC"  # Timezone for run time
